### ISSUE TITLE
list_users is not recognized in store.fga.yaml files

### ISSUE THREAD

**Issue by aaguiarz** [openfga/vscode-ext#295] opened 2024-09-08 21:30 UTC
When writing tests for list_users in the `.fga.yaml` file, the `list_users` key is not recognized in Visual Studio Code:

<img width="738" alt="image" src="https://github.com/user-attachments/assets/35c30fdb-2a27-4dcd-adf4-bd5fb850c63d">

**Comment by ewanharris** [comment] 2024-09-09 17:23
@aaguiarz do you have an older extension installed manually by chance? We added support in #232 and it appears functional for me in [this store file](https://github.com/openfga/cli/blob/main/example/store_abac.fga.yaml)

![image](https://github.com/user-attachments/assets/bcd2a586-e535-4169-a736-3e38652e8ee5)

**Comment by aaguiarz** [comment] 2024-09-09 17:30
I see the error in that file too:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/93f68998-4056-4858-99ba-43f06a2dd35f">

**Comment by ewanharris** [comment] 2024-09-10 17:19
@aaguiarz I'm not really sure what would be the difference here as the extensions should functionally be the same. We just shipped `0.2.23` so could you try updating to that and see if the issue persists

**Comment by Siddhant-K-code** [comment] 2024-09-14 08:09
@ewanharris, I think, it got broke in https://github.com/openfga/vscode-ext/pull/270 while migrating to `@openfga/syntax-transformer`. Because, in #270, we removed the schema file which also has `ListUsersRequest` which was introduced in #232, but can't find similar Lines of Code for `list_users` in the `syntax-transformer` package and neither in [this file](https://github.com/openfga/vscode-ext/blob/main/server/src/yaml-utils.ts).

**Comment by ewanharris** [comment] 2024-09-14 10:07
@Siddhant-K-code The store validation was moved across to language in openfga/language/pull/286, and for JS is in [validate-store.ts](https://github.com/openfga/language/blob/main/pkg/js/validator/validate-store.ts) which provides the `validator.YamlStoreValidator()` we now use.

**Comment by ewanharris** [comment] 2024-09-23 15:40
Closing as confirmed no longer able to reproduce.

**Closed by ewanharris** 2024-09-23 15:40 UTC
